package ch.ethz.jadabs.im.db.auto;

/** Class _NewAccount was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _NewAccount extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String PASSWORD_PROPERTY = "password";

    public static final String EMAIL_PK_COLUMN = "email";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }
    
    
    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }
    
    
}
