// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package example.serverscript.connector;

public interface Interface extends java.rmi.Remote {
	public java.lang.String request(java.lang.String string_1, java.lang.String string_2) throws java.rmi.RemoteException;

}
