#! /bin/bash

# -Dprodtest 
# -Dw_proxy 

java -Djxme.peername=peer2 -Dprodtest -Dw_proxy \
  -Djava.class.path=$OSGI_KF:/home/andfrei/.maven/repository/nanning/jars/nanning-core-1.0-beta-1.jar \
  org.knopflerfish.framework.Main -xargs es-min-init.xargs
  